version: '3.5'

services:
  app:
    container_name: ENVIRONMENT-NAME-PROJECT-NAME
    image: IMAGE-NAME:IMAGE-TAG
    volumes:
      - MOUNT-DATA-FOLDER/PROJECT-NAME:/media
    ports:
      - P-MAPPING:8080
    restart: unless-stopped
    pull_policy: always
